puphpet.extension.magento.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionMagentoBundle:Front:index }

puphpet.extension.magento.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionMagentoBundle:Manifest:index }
